# Generated by Django 2.2.28 on 2023-02-09 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_category_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='veiws',
            new_name='views',
        ),
    ]
